#!/bin/bash

MARK=$(head -n 1 ./boot/mark)
BACKUP_SUFFIX=$(date +"%Y-%m-%dT%H-%M-%S")

if [[ "$MARK" == "0" ]]; then
        echo "Update apt database..."
        sudo apt update
fi

if [[ "$MARK" == "0" && "$1" != "lite" && "$2" != "lite" ]]; then
    echo "1" > ./boot/mark
    echo 'To reinstall driver exectue "echo 0 > ./boot/mark" and rerun the script.'
    
    echo "Installing evdev..."
    sudo apt-get install xserver-xorg-input-evdev
    sudo cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf
    
    echo "Installing cmake..."
    sudo apt-get install cmake -y
    
    echo "Building fbcp..."
    mkdir -p ./rpi-fbcp/build/
    cd ./rpi-fbcp/build/
    sudo cmake ..
    sudo make
    echo "installing fbcp..."
    sudo install fbcp /usr/local/bin/fbcp
    cd ../../
    
    echo "installing xinput-calibrator..."
    sudo apt-get install -y xinput-calibrator
    
    sudo mkdir -p /usr/share/X11/xorg.conf.d
elif [[ "$MARK" == "0" && "$1" = "lite" ]]; then
    echo "1" > ./boot/mark
    echo "No touch driver installled"
    echo "No fbcp driver installled"
    sudo mkdir -p /usr/share/X11/xorg.conf.d
fi

if [[ "$MARK" == "0" ]]; then
    echo "Installing rc.local and fbturbo..."
    sudo cp /etc/rc.local "/etc/rc.local.backup-$BACKUP_SUFFIX"
    if [[ "$1" != "lite" && "$2" != "lite" ]]; then
        sudo cp -rf ./etc/rc.local-gpio /etc/rc.local
        sudo cp -rf ./usr/share/X11/xorg.conf.d/99-fbturbo.conf-HDMI  /usr/share/X11/xorg.conf.d/99-fbturbo.conf
    else
        sudo cp -rf ./etc/rc.local /etc/rc.local
        sudo cp -rf ./usr/share/X11/xorg.conf.d/99-fbturbo.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf
    fi

    echo "Compile overlays..."
    dtc -O dtb -o waveshare35a-overlay.dtb waveshare35a.dts
    
    echo "Install overlays..."
    sudo cp ./waveshare35a-overlay.dtb /boot/overlays/waveshare35a.dtbo
    sudo cp ./waveshare35a-overlay.dtb /boot/overlays/
    
    echo "Fixing cmdline.txt parameters (file will be OVERWRITTEN)..."
    sudo cp /boot/cmdline.txt "/boot/cmdline.txt.backup-$BACKUP_SUFFIX"
    if [ -b /dev/mmcblk0p7 ]; then
        sudo cp ./cmdline.txt-noobs /boot/cmdline.txt
    else
        sudo cp ./cmdline.txt /boot/
    fi
    
    echo "Fixing /etc/inittab (file will be OVERWRITTEN)..."
    sudo cp /etc/inittab "/etc/inittab.backup-$BACKUP_SUFFIX" || echo "no existing inittab (skipping backup)"
    sudo cp ./inittab /etc/
    
    echo "Driver installation is completed!"
fi

if [[ "$1" == "0" || "$#" == "0" || "$2" == "0" ]]; then
    sudo cp -rf ./etc/X11/xorg.conf.d/99-calibration.conf-35  /usr/share/X11/xorg.conf.d/99-calibration.conf
    sudo cp ./boot/config-35.txt /boot/config.txt
    echo "LCD configure 0"
elif [[ "$1" == "lite" && "$#" = "1" ]]; then
    sudo cp -rf ./etc/X11/xorg.conf.d/99-calibration.conf-35  /usr/share/X11/xorg.conf.d/99-calibration.conf
    sudo cp ./boot/config-35.txt /boot/config.txt
    echo "LCD configure 0"
elif [[ "$1" == "90" || "$2" == "90" ]]; then
    if [[ "$1" == "lite" || "$2" == "lite" ]]; then
        sudo cp ./boot/config-35.txt-90-lite /boot/config.txt
    else
        sudo cp ./boot/config-35.txt-90 /boot/config.txt
    fi
    sudo cp -rf ./etc/X11/xorg.conf.d/99-calibration.conf-35-270  /usr/share/X11/xorg.conf.d/99-calibration.conf
    echo "LCD configure 90"
elif [[ "$1" == "180" || "$2" == "180" ]]; then
    if [[ "$1" == "lite" || "$2" == "lite" ]]; then
        sudo cp ./boot/config-35.txt-180-lite /boot/config.txt
    else
        sudo cp ./boot/config-35.txt-180 /boot/config.txt
    fi
    sudo cp -rf ./etc/X11/xorg.conf.d/99-calibration.conf-35-180  /usr/share/X11/xorg.conf.d/99-calibration.conf
    echo "LCD configure 180"
elif [[ "$1" == "270" || "$2" == "270" ]]; then
    if [[ "$1" == "lite" || "$2" == "lite" ]]; then
        sudo cp ./boot/config-35.txt-270-lite /boot/config.txt
    else
        sudo cp ./boot/config-35.txt-270 /boot/config.txt
    fi
    sudo cp -rf ./etc/X11/xorg.conf.d/99-calibration.conf-35-90  /usr/share/X11/xorg.conf.d/99-calibration.conf
    echo "LCD configure 270"
fi


if test "$#" = "0" -o "$1" = "0" -o "$1" = "90"  -o "$1" = "180" -o "$1" = "270" -o "$2" = "0" -o "$2" = "90"  -o "$2" = "180" -o "$2" = "270" -o "$1" = "lite" -o "$2" = "lite" ; then
    echo "REBOOT for changes to take effect e.g. 'sudo reboot'"
else
    echo "Invalid parameter, Usage:LCD35-show [0] [90] [180] [270] [lite]"
fi
